version: '3.0'

services:
  grafana:
    container_name: 'bohemiaautomation-evaics-app'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-9.5.2}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/bohemiaautomation-evaics-app
      - ./provisioning:/etc/grafana/provisioning
